main: process_numbers.cpp
	echo     ------------compiling process_numbers.cpp to create executable program main----------------
	g++  -ggdb   -std=c++11   process_numbers.cpp   -o   numbers
clean:
	echo ----------------removing executable program main--------------------
	/bin/rm numbers
