main: mapset.cpp
	echo     ------------compiling mapset.cpp to create executable program main----------------
	g++  -ggdb   -std=c++11   mapset.cpp   -o   mapset
clean:
	echo ----------------removing executable program main--------------------
	/bin/rm mapset
