main: SegregateColors.cpp
	echo     ------------compiling SegregateColors.cpp to create executable program main----------------
	g++  -ggdb   -std=c++11   SegregateColors.cpp   -o   SegregateColors
clean:
	echo ----------------removing executable program main--------------------
	/bin/rm SegregateColors
