main: TruckProblem.cpp
	echo     ------------compiling TruckProblem.cpp to create executable program main----------------
	g++  -ggdb   -std=c++11   TruckProblem.cpp   -o   TruckProblem
clean:
	echo ----------------removing executable program main--------------------
	/bin/rm TruckProblem
