main: SubarrayofLargestSum.cpp
	echo     ------------compiling SubarrayofLargestSum.cpp to create executable program main----------------
	g++  -ggdb   -std=c++11   SubarrayofLargestSum.cpp   -o   SubarrayofLargestSum
clean:
	echo ----------------removing executable program main--------------------
	/bin/rm SubarrayofLargestSum
