main: dijkstra.cpp
	echo     ------------compiling dijkstra.cpp to create executable program main----------------
	g++  -ggdb   -std=c++11   dijkstra.cpp   -o   dijkstra
clean:
	echo ----------------removing executable program main--------------------
	/bin/rm dijkstra
