main: mst.cpp
	echo     ------------compiling mst.cpp to create executable program main----------------
	g++  -ggdb   -std=c++11   mst.cpp   -o   mst
clean:
	echo ----------------removing executable program main--------------------
	/bin/rm mst
