main: HeuristicSearch.cpp
	echo     ------------compiling HeuristicSearch.cpp to create executable program main----------------
	g++  -ggdb   -std=c++11   HeuristicSearch.cpp   -o   HeuristicSearch
clean:
	echo ----------------removing executable program main--------------------
	/bin/rm HeuristicSearch
