main: RotatedArray.cpp
	echo     ------------compiling RotatedArray.cpp to create executable program main----------------
	g++  -ggdb   -std=c++11   RotatedArray.cpp   -o   RotatedArray
clean:
	echo ----------------removing executable program main--------------------
	/bin/rm RotatedArray
