main: product.cpp
	echo     ------------compiling product.cpp to create executable program main----------------
	g++  -ggdb   -std=c++11   product.cpp   -o   product
clean:
	echo ----------------removing executable program main--------------------
	/bin/rm product

